name: Run Bot tasks
on:
  schedule:
    - cron: "0 11 * * 4"  # every Thursday at 7 AM Eastern

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Decrypt secrets
        run: ./.github/scripts/decrypt.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run Bot
        run: |
          pip install -r requirements.txt
          python run.py
