name: Run Bot tasks
on:
  schedule:
    - cron: "0 13 * * 3"  # every Wednesday at 9 AM Eastern

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Decrypt secrets
        run: ./.github/scripts/decrypt.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run Bot
        run: |
          pip install -r requirements.txt
          python run.py
